env:
  # For default users
  # cache_root: "cache"
  # For internal use with per/ent storage
  # cache_root: "/export/home/.cache/minigpt4"
  # cache_root: "/home/////.cache/minigpt4"
  cache_root: "/data///.cache/minigpt4"
